services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
      - react
      - pacman
    networks:
      - inception
    restart: always

  react:
    build: ./requirements/react
    image: react
    container_name: react
    networks:
      - inception
    restart: always

  pacman:
    build: ./requirements/pacman
    image: pacman
    container_name: pacman
    volumes:
      - pacman_data:/root/.local/share/pacman_game
    networks:
      - inception
    restart: always

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind
  pacman_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/pacman
      o: bind

networks:
  inception:
    driver: bridge
